// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewCacher creates a new instance of Cacher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cacher {
	mock := &Cacher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Cacher is an autogenerated mock type for the Cacher type
type Cacher struct {
	mock.Mock
}

type Cacher_Expecter struct {
	mock *mock.Mock
}

func (_m *Cacher) EXPECT() *Cacher_Expecter {
	return &Cacher_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type Cacher
func (_mock *Cacher) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cacher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Cacher_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Cacher_Expecter) Close() *Cacher_Close_Call {
	return &Cacher_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Cacher_Close_Call) Run(run func()) *Cacher_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Cacher_Close_Call) Return(err error) *Cacher_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cacher_Close_Call) RunAndReturn(run func() error) *Cacher_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function for the type Cacher
func (_mock *Cacher) Retrieve(ctx context.Context, uri string) ([]byte, error) {
	ret := _mock.Called(ctx, uri)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, uri)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uri)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cacher_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type Cacher_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx context.Context
//   - uri string
func (_e *Cacher_Expecter) Retrieve(ctx interface{}, uri interface{}) *Cacher_Retrieve_Call {
	return &Cacher_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx, uri)}
}

func (_c *Cacher_Retrieve_Call) Run(run func(ctx context.Context, uri string)) *Cacher_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cacher_Retrieve_Call) Return(data []byte, err error) *Cacher_Retrieve_Call {
	_c.Call.Return(data, err)
	return _c
}

func (_c *Cacher_Retrieve_Call) RunAndReturn(run func(ctx context.Context, uri string) ([]byte, error)) *Cacher_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type Cacher
func (_mock *Cacher) Store(ctx context.Context, uri string, data []byte) error {
	ret := _mock.Called(ctx, uri, data)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, uri, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cacher_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type Cacher_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - uri string
//   - data []byte
func (_e *Cacher_Expecter) Store(ctx interface{}, uri interface{}, data interface{}) *Cacher_Store_Call {
	return &Cacher_Store_Call{Call: _e.mock.On("Store", ctx, uri, data)}
}

func (_c *Cacher_Store_Call) Run(run func(ctx context.Context, uri string, data []byte)) *Cacher_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cacher_Store_Call) Return(err error) *Cacher_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cacher_Store_Call) RunAndReturn(run func(ctx context.Context, uri string, data []byte) error) *Cacher_Store_Call {
	_c.Call.Return(run)
	return _c
}
