// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewFetcher creates a new instance of Fetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Fetcher {
	mock := &Fetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

type Fetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *Fetcher) EXPECT() *Fetcher_Expecter {
	return &Fetcher_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type Fetcher
func (_mock *Fetcher) Fetch(ctx context.Context, uri string) ([]byte, error) {
	ret := _mock.Called(ctx, uri)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, uri)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uri)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Fetcher_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type Fetcher_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - uri string
func (_e *Fetcher_Expecter) Fetch(ctx interface{}, uri interface{}) *Fetcher_Fetch_Call {
	return &Fetcher_Fetch_Call{Call: _e.mock.On("Fetch", ctx, uri)}
}

func (_c *Fetcher_Fetch_Call) Run(run func(ctx context.Context, uri string)) *Fetcher_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Fetcher_Fetch_Call) Return(data []byte, err error) *Fetcher_Fetch_Call {
	_c.Call.Return(data, err)
	return _c
}

func (_c *Fetcher_Fetch_Call) RunAndReturn(run func(ctx context.Context, uri string) ([]byte, error)) *Fetcher_Fetch_Call {
	_c.Call.Return(run)
	return _c
}
