// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tahardi/pluckmd/internal/pluck"
)

// NewPlucker creates a new instance of Plucker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlucker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Plucker {
	mock := &Plucker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Plucker is an autogenerated mock type for the Plucker type
type Plucker struct {
	mock.Mock
}

type Plucker_Expecter struct {
	mock *mock.Mock
}

func (_m *Plucker) EXPECT() *Plucker_Expecter {
	return &Plucker_Expecter{mock: &_m.Mock}
}

// Pluck provides a mock function for the type Plucker
func (_mock *Plucker) Pluck(ctx context.Context, code string, name string, kind pluck.Kind) (string, error) {
	ret := _mock.Called(ctx, code, name, kind)

	if len(ret) == 0 {
		panic("no return value specified for Pluck")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, pluck.Kind) (string, error)); ok {
		return returnFunc(ctx, code, name, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, pluck.Kind) string); ok {
		r0 = returnFunc(ctx, code, name, kind)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, pluck.Kind) error); ok {
		r1 = returnFunc(ctx, code, name, kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Plucker_Pluck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pluck'
type Plucker_Pluck_Call struct {
	*mock.Call
}

// Pluck is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - name string
//   - kind pluck.Kind
func (_e *Plucker_Expecter) Pluck(ctx interface{}, code interface{}, name interface{}, kind interface{}) *Plucker_Pluck_Call {
	return &Plucker_Pluck_Call{Call: _e.mock.On("Pluck", ctx, code, name, kind)}
}

func (_c *Plucker_Pluck_Call) Run(run func(ctx context.Context, code string, name string, kind pluck.Kind)) *Plucker_Pluck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 pluck.Kind
		if args[3] != nil {
			arg3 = args[3].(pluck.Kind)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Plucker_Pluck_Call) Return(snippet string, err error) *Plucker_Pluck_Call {
	_c.Call.Return(snippet, err)
	return _c
}

func (_c *Plucker_Pluck_Call) RunAndReturn(run func(ctx context.Context, code string, name string, kind pluck.Kind) (string, error)) *Plucker_Pluck_Call {
	_c.Call.Return(run)
	return _c
}
